name: RodargQueue
version: 1.0
api-version: 1.16
main: io.rodarg.queue.Main
permissions:
  queue.skip:
    description: skip the queue
    default: op
  queue.priority:
    description: join the priority queue
    default: op
commands:
  skip:
    description: Skip queue
    usage: /skip